blank_issues_enabled: false
contact_links:
  - name: 📚 Dokumentation
    url: https://github.com/moham/portfolio/wiki
    about: Schaue dir die Projektdokumentation an
  - name: 💬 Diskussion
    url: https://github.com/moham/portfolio/discussions
    about: Stelle Fragen oder diskutiere Ideen

